name: my_mind
description: A new Flutter project.

version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  shared_preferences: ^0.4.3
  flutter_dotenv: ^2.1.0
  cpf_cnpj_validator: ^ 1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
